name: Compile MSP430 Code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: slimboot/msp430-gcc:latest  # Gotowe Å›rodowisko z kompilatorem

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          # Kompilacja do formatu ELF
          msp430-elf-gcc -mmcu=msp430fr5739 -O2 -g -o main.elf AgNP04b-main.c
          
          # Konwersja do formatu Intel HEX (wymaganego przez PCBWay)
          msp430-elf-objcopy -O ihex main.elf main.hex

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: main.hex
