name: Compile MSP430 Code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSP430 GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-msp430 binutils-msp430 msp430-libc

      - name: Build project
        run: make

      - name: Upload Hex File
        uses: actions/upload-artifact@v3
        with:
          name: firmware-hex
          path: main.hex
          
