name: Compile MSP430 Code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSP430 Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-msp430 binutils-msp430 msp430-libc

      - name: Build project
        run: |
          # Kompilacja do pliku .elf
          msp430-elf-gcc -mmcu=msp430fr5739 -O2 -g -o main.elf AgNP04b-main.c
          # Konwersja na format Intel HEX dla PCBWay
          msp430-elf-objcopy -O ihex main.elf main.hex

      - name: Upload Hex File
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: main.hex
