nname: Compile MSP430 Code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSP430 Toolchain
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y gcc-msp430 binutils-msp430 msp430-libc msp430mcu-lib

      - name: Build project
        run: |
          # Kompilacja z flagą -I aby upewnić się, że widzi biblioteki
          msp430-elf-gcc -mmcu=msp430fr5739 -O2 -g -o main.elf AgNP04b-main.c
          
          # Konwersja na format Intel HEX
          msp430-elf-objcopy -O ihex main.elf main.hex
          
          # Sprawdzenie czy plik powstał
          ls -lh main.hex

      - name: Upload Hex File
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: main.hex
